version: 0.2

phases:
  install:
    commands:
      - aws cloudformation package --template-file searchLambda.template.yaml --s3-bucket photo-app-s3-for-artifacts --output-template-file searchLambda.yaml
artifacts:
  files:
    - "searchLambda.template.yaml"
    - "searchLambda.yaml"